[theme]
primaryColor = "#1f8a62"
backgroundColor = "#f3f5f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#182230"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
